version: '3'

services:
  # Soil TCP Monitor Service
  soil-tcp-monitor:
    restart: unless-stopped
    command: python -m examples.soil_tcp_monitor
    environment:
      - MODBUS_HOST=192.168.2.4
      - MODBUS_PORT=502
    volumes:
      - ./.env:/app/.env